### ISSUE TITLE
Code of conduct, license, etc.

### ISSUE THREAD

**Issue by jpatton-USGS** [usgs/pager#171]
- Need to modify LICENSE.md to match latest USGS best practices
- Need to add DISCLAMER.md, and code metatdata to match latest USGS best practices
- Should add CONTRIBUTING.md and CODE_OF_CONDUCT.md to match latest USGS best practices

See Me or Eric Martinez's email for examples.

**Comment by mhearne-usgs** [comment]
Adding these in the release_final branch.
