### ISSUE TITLE
Incomplete PAGER URL in email

### ISSUE THREAD

**Issue by kmarano-usgs** [usgs/pager#192]
When an email is sent for a PAGER version > 1, the URL at the end of the long and pdf message is http://earthquake.usgs.gov/data/pager/ instead of the long URL, such as https://earthquake.usgs.gov/earthquakes/eventpage/us20009mbt#pager.

Example events:
us20009ly0
us2000atjv
us10009757

**Comment by mhearne-usgs** [comment]
This was closed in a previous PR.
