### ISSUE TITLE
Create more methods for getting pager data 

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/pager#29]
These are three dictionaries that would are useful: 
PagerData._pagerdict['pager']
PagerData._pagerdict['comments']
PagerData._pagerdict['population_exposure']

**Comment by mhearne-usgs** [comment]
- Added a getPagerInfo() method
 - getImpactComments(), getStructureComment(), getSecondaryComment(), getHistoricalComment() methods already exist.
 - getTotalExposure() method already exists.
