### ISSUE TITLE
Eventid problem

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/pager#32]
[This](http://earthquake.usgs.gov/archive/product/shakemap/atlas20041226005853/atlas/1477012710245/download/grid.xml) event is a problem. Looks to my like the problem is really in the grid.xml file because event_network is set to "ussource_network : us".  So this likely isn't really a problem with pager code but with the online data.

**Comment by mhearne-usgs** [comment]
I agree with Eric's assessment.  We should fix this issue in the Atlas.
