### ISSUE TITLE
Pager fail

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/pager#33]
Basic pager run fails on [this](http://earthquake.usgs.gov/archive/product/shakemap/usb000ief9/us/1373922987995/download/grid.xml) grid.xml file:

`INFO:PagerLog:Creating SMTP handler with gscodens01.cr.usgs.gov,pager@usgs.gov,['emthompson@usgs.gov'],PAGER Error
INFO:PagerLog:Creating event directory
INFO:PagerLog:Population year: 2013 Population file: /Users/emthompson/pager/data/lspop2013.flt

INFO:PagerLog:Calculating population exposure.
INFO:PagerLog:Calculating empirical fatalities.
INFO:PagerLog:Calculating economic exposure.
INFO:PagerLog:Calculating semi-empirical fatalities.
INFO:PagerLog:Getting all comments.
INFO:PagerLog:Drawing probability plots.
INFO:PagerLog:Generating exposure map...
INFO:PagerLog:Traceback (most recent call last):

INFO:PagerLog:  File "./pager", line 220, in main

INFO:PagerLog:exposure_base)
INFO:PagerLog:  File "/Users/emthompson/src/python/pager/losspager/vis/contourmap2.py", line 444, in draw_contour

INFO:PagerLog:mapcities = mapcities.limitByMapCollision2(ax,10.0)
INFO:PagerLog:  File "/Users/emthompson/anaconda/envs/pager/lib/python3.5/site-packages/impactutils/mapping/cartopycity.py", line 69, in limitByMapCollision2

INFO:PagerLog:if not np.isnan(lefts[0]):
INFO:PagerLog:IndexError
INFO:PagerLog::
INFO:PagerLog:index 0 is out of bounds for axis 0 with size 0
INFO:PagerLog:
During handling of the above exception, another exception occurred:

INFO:PagerLog:Traceback (most recent call last):

INFO:PagerLog:  File "./pager", line 321, in <module>

INFO:PagerLog:main(args,config)
INFO:PagerLog:  File "./pager", line 250, in main

INFO:PagerLog:msg = errobj
INFO:PagerLog:NameError
INFO:PagerLog::
INFO:PagerLog:name 'errobj' is not defined`

**Comment by mhearne-usgs** [comment]
Fixed.
